version: 0.0
os: linux
files:
  - source: /
    destination: /srv/slash_payment
permissions:
  - object: /srv/slash_payment
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 180
  ValidateService:
    - location: scripts/start_server.sh
      timeout: 360