Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: epay

  Environment:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
    Default: stg

  TrafficType:
    Description: The type of traffic to log.
    Type: String
    Default: ALL
    AllowedValues: [ ACCEPT, REJECT, ALL ]

  RetentionInDays:
    Description: The number of days to retain the log events in the specified log group.
    Type: Number
    Default: 30
    AllowedValues: [ 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653 ]

  StackName:
    Type: String
    Description: Name of the stack
    Default: stg-epay

Resources:
  VpcFlowLogs:
    Type: "AWS::EC2::FlowLog"
    Properties:
      ResourceType: "VPC"
      ResourceId:
        Fn::ImportValue: !Sub '${Environment}-${ProjectName}-VPC'
      TrafficType: !Ref TrafficType
      DeliverLogsPermissionArn: !GetAtt VpcFlowLogsIamRole.Arn
      LogGroupName: !Ref VpcFlowLogsLogGroup

  VpcFlowLogsLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub '${Environment}-${ProjectName}-VpcFlowLogsLogGroup'
      RetentionInDays: !Ref RetentionInDays

  VpcFlowLogsIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub '${Environment}-${ProjectName}-VpcFlowLogsIamRole'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "vpc-flow-logs.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub '${Environment}-${ProjectName}-VpcFlowLogsIamRole-Policies'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                Resource: "*"